server:
  port: 8090
  servlet:
    context-path: /imea-systems
spring:
  application:
    name: ${SERVICE_NAME:order-service}
  datasource:
    url: jdbc:h2:mem:imeasystems
    username: sa
    password: Strong.Pwd-123
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        type: DEBUG
